using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Windows;

namespace testBenchGenerator.Model
{
    public class FileGen
    {
        #region constant SystemVerilog strings, other often used strings
        private const string timescale = "`timescale 1ns / 1ps";
        private const string nettypeBegin = "`default_nettype none";
        private const string nettypeEnd = "`default_nettype wire";
        private const string always = "\talways @(posedge ";
        private const string task = "\ttask ";
        private const string endtask = "\tendtask";
        private const string endmodule = "endmodule";
        private const string initial = "\tinitial begin";
        private const string forever = "\t\tforever begin";
        private const string end = "\tend";
        private const string generatedComment = "//GENERATED CODE";
        private const string generatedToAdaptComment = "//GENERATED CODE TO ADAPT";
        #endregion
        #region private variables
        private ModuleFile moduleFile;
        private string tbFileName;
        private List<string> lines;
        private string formatOut;
        private string formatIn;
        private string dos;
        private string dis;
        #endregion
        #region public properties
        public ModuleFile ModuleFile
        {
            get { return this.moduleFile; }
            set { this.moduleFile = value; }
        }

        public string TbFileName
        {
            get { return this.tbFileName; }
            set { this.tbFileName = value; }
        }

        #endregion
        #region helper methods

        private bool SaveFile()
        {
            try
            {
                if (File.Exists(this.TbFileName))
                {
                    File.Delete(this.TbFileName);
                }

                // Create a new file     
                using (FileStream fs = File.Create(this.TbFileName))
                {
                }
                using (System.IO.StreamWriter file =
                    new System.IO.StreamWriter(this.TbFileName))
                {
                    foreach (string line in this.lines)
                    {
                        file.WriteLine(line);
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                return false;
            }
            return true;
        }

        private void FormatsForFileIO(TestCase di)
        {
            this.formatIn = String.Empty;
            this.formatOut = String.Empty;
            this.dis = String.Empty;
            this.dos = String.Empty;
            foreach(Port inp in di.DataIns)
            {
                this.formatIn += di.Radix == Radix.Decimal ? "%d" : "%h";
                this.dis += inp.Name;
                if (inp == di.DataIns.LastOrDefault())
                {
                    this.formatIn += "\\n";
                    this.dis += ");";
                }
                else
                {
                    this.formatIn += " ";
                    this.dis += ", ";
                }
            }
            foreach (Port outp in di.DataOuts)
            {
                formatOut += di.Radix == Radix.Decimal ? "%d" : "%h";
                dos += outp.Name;
                if (outp == di.DataOuts.LastOrDefault())
                {
                    formatOut += "\\n";
                    dos += ");";
                }
                else
                {
                    formatOut += " ";
                    dos += ", ";
                }
            }
        }

        #endregion
        #region lines create methods

        private void AddHeader()
        {
            this.lines.Add("////////////////////////////////////////////////////////////////////////////////");
            this.lines.Add("//                                                                            //");
            this.lines.Add("//                                                                            //");
            this.lines.Add("//                        FILE GENERATED BY tbGen TOOL                        //");
            this.lines.Add("//                 (C) Copyright by Vigogne Software Ltd. 2020                //");
            this.lines.Add("//                                                                            //");
            this.lines.Add("//                                                                            //");
            this.lines.Add("//  Please review the content of this file before compilation and execution.  //");
            this.lines.Add("//                                                                            //");
            this.lines.Add("//                                                                            //");
            this.lines.Add("////////////////////////////////////////////////////////////////////////////////");
            this.lines.Add(timescale);
            this.lines.Add(nettypeBegin);
            this.lines.Add("");

            this.lines.Add("module " + this.TbFileName.Split('\\').ToList<string>().LastOrDefault().Replace(".sv", "();").Replace(".v", "();"));
            this.lines.Add("");
        }

        private void AddFooter()
        {
            this.lines.Add("//USER CODE");
            this.lines.Add("//Place for your stimulus & verification logic");
            this.lines.Add("");
            this.lines.Add("");
            this.lines.Add(endmodule);
            this.lines.Add(nettypeEnd);
        }

        private void AddParamsAndConnections()
        {
            if (this.ModuleFile.Parameters.Count > 0)
            {
                this.lines.Add(generatedToAdaptComment);
                this.lines.Add("//Parameters of Device Under Test - change values if needed");
            }
            foreach (Parameter par in this.ModuleFile.Parameters)
            {
                this.lines.Add("\tlocalparam " + par.Name + " = " + par.Value + ";");
            }
            this.lines.Add("");
            this.lines.Add(generatedToAdaptComment);
            this.lines.Add("//Clock signals period - change for proper values");
            foreach (Clock clk in this.ModuleFile.Clocks)
            {
                if (clk.Frequency != 0.0)
                    this.lines.Add("\tlocalparam " + clk.Name.ToUpper() + "_PERIOD = " + (1000 / clk.Frequency).ToString("N3").Replace(",",".") + "ns;");
            }
            this.lines.Add("");
            this.lines.Add(generatedComment);
            this.lines.Add("//Connections of Device Under Test");
            foreach (Port conn in this.ModuleFile.Inputs)
            {
                string lineToAdd = "\tlogic\t";
                if (conn.Bitwidth != null)
                {
                    lineToAdd += conn.Bitwidth;
                    for (int i = this.ModuleFile.BwLen - (conn.Bitwidth.Length / 4); i > 0; i--)
                        lineToAdd += "\t";
                }
                else
                {
                    for (int i = this.ModuleFile.BwLen; i > 0; i--)
                        lineToAdd += "\t";
                }
                this.lines.Add(lineToAdd + "\t" + conn.Name + " = '0;");
            }
            foreach (Port conn in this.ModuleFile.Outputs)
            {
                string lineToAdd = "\tlogic\t";
                if (conn.Bitwidth != null)
                {
                    lineToAdd += conn.Bitwidth;
                    for (int i = this.ModuleFile.BwLen - (conn.Bitwidth.Length / 4); i > 0; i--)
                        lineToAdd += "\t";
                }
                else
                {
                    for (int i = this.ModuleFile.BwLen; i > 0; i--)
                        lineToAdd += "\t";
                }
                this.lines.Add(lineToAdd + "\t" + conn.Name + ";");
            }
            this.lines.Add("");
        }

        private void AddDut()
        {
            this.lines.Add(generatedComment);
            this.lines.Add("//Device Under Test instatiation");
            if (this.ModuleFile.Parameters.Count > 0)
            {
                this.lines.Add("\t" + this.ModuleFile.Name + " #(");
                foreach (Parameter par in this.ModuleFile.Parameters)
                {
                    if (par == this.ModuleFile.Parameters.Last())
                        this.lines.Add("\t\t." + par.Name + "(" + par.Name + ")");
                    else
                        this.lines.Add("\t\t." + par.Name + "(" + par.Name + "),");
                }
                this.lines.Add("\t) dut(");
            }
            else
            {
                this.lines.Add("\t" + this.ModuleFile.Name + " dut(");
            }
            foreach (Port conn in this.ModuleFile.Inputs)
            {
                this.lines.Add("\t\t." + conn.Name + "(" + conn.Name + "),");
            }
            foreach (Port conn in this.ModuleFile.Outputs)
            {
                if (conn == this.ModuleFile.Outputs.Last())
                    this.lines.Add("\t\t." + conn.Name + "(" + conn.Name + ")");
                else
                    this.lines.Add("\t\t." + conn.Name + "(" + conn.Name + "),");
            }
            this.lines.Add("\t);");
            this.lines.Add("");
        }

        private void AddClocks()
        {
            this.lines.Add(generatedComment);
            this.lines.Add("//Clocks generation");            
            foreach (Clock clk in this.ModuleFile.Clocks)
            {
                this.lines.Add(initial);
                this.lines.Add(forever);
                if (clk.Frequency != 0.0)
                {
                    this.lines.Add("\t\t\t#(" + clk.Name.ToUpper() + "_PERIOD / 2) " + clk.Name + " <= ~" + clk.Name + ";");
                }
                this.lines.Add("\t" + end);
                this.lines.Add(end);
            }            
            this.lines.Add("");
        }

        private void AddResets()
        {
            this.lines.Add("\t\t//Initial resets conditions");
            foreach (Reset rst in this.ModuleFile.Resets)
            {
                this.lines.Add("\t\t" + rst.Name + " = " + (rst.Polarization ? "1'b1;" : "1'b0;"));
            }
            this.lines.Add("\t\t#100ns;");
            foreach (Reset rst in this.ModuleFile.Resets)
            {
                this.lines.Add("\t\t" + rst.Name + " = " + (rst.Polarization ? "1'b0;" : "1'b1;"));
            }
        }

        private void AddInputsInit()
        {
            this.lines.Add("\t\t//Initial inputs states - adapt to your needs");
            foreach (Port input in this.ModuleFile.Inputs)
            {
                if ((!this.ModuleFile.Resets.Any(r => r.Name == input.Name)) && !(this.ModuleFile.Clocks.Any(r => r.Name == input.Name)))
                {
                    this.lines.Add("\t\t" + input.Name + " = '0;");
                }
            }
        }

        private void AddInitialBlock()
        {
            this.lines.Add(generatedToAdaptComment);
            this.lines.Add("//Initial connections' conditions, initial reset state, files' opening and test tasks");
            this.lines.Add(initial);
            this.AddInputsInit();
            this.AddResets();
            if (this.ModuleFile.TestCases.Any(di => di.DataVector != null))
            {
                this.lines.Add("\t\tfork");
                foreach (TestCase di in this.ModuleFile.TestCases)
                {
                    if (di.DataVector != null && di.DataIns.FirstOrDefault() != null)
                    {
                        this.lines.Add("\t\t\t" + di.DataIns.FirstOrDefault().Name + "_" + di.DataVector.Split('\\').LastOrDefault().Replace(".txt", "();"));
                    }
                }
                this.lines.Add("\t\tjoin");
            }
            this.lines.Add(end);
            this.lines.Add("");
        }

        private void AddFileOutput()
        {
            if (this.ModuleFile.TestCases.Any(di => di.DataVector != null))
            {
                this.lines.Add(generatedToAdaptComment);
                this.lines.Add("//Tasks for writingto output data files - modify for your needs");
                foreach (TestCase di in this.ModuleFile.TestCases)
                {
                    if (di.DataVector != null)
                    {
                        string name = this.ModuleFile.Name + "_" + di.DataOutVector.Split('\\').LastOrDefault().Replace(".txt", "");

                        this.lines.Add(task + name + "();");

                        if(!di.Loop)
                        {
                            int linesCount = File.ReadAllLines(di.DataVector).Length;
                            this.lines.Add("\t\tinteger num_lines_" + name + " = " + linesCount + ";");
                            this.lines.Add("\t\tinteger num_vlds_" + name + " = 0;");
                        }
                        this.lines.Add("\t\tinteger fid_out_" + name + " = $fopen(" + di.DataOutVector.Replace("\\", "/") + "\",\"w\");");
                        this.lines.Add("\t\tif(fid_out_" + name + " == 0) begin");
                        this.lines.Add("\t\t\t$display(\"Error opening file - could not open.\");");
                        this.lines.Add("\t\t\t$stop;");
                        this.lines.Add("\t" + end + " else begin");
                        this.lines.Add("\t\t\t$display(\"File " + di.DataVector.Replace("\\", "/") + " opened successfully.\");");
                        this.lines.Add("\t" + end);
                        this.FormatsForFileIO(di);

                        if (di.Loop)
                        {
                            this.lines.Add(forever);
                            this.lines.Add("\t\t\t@posedge(" + di.ClockSync.Name + ");");
                            this.lines.Add("\t\t\tif(" + di.ValidOut.Name + ") begin");                            
                            this.lines.Add("\t\t\t\t$fdisplay(fid_out_" + name + ", \"" + this.formatOut + "\", " + this.dos);
                            this.lines.Add("\t\t" + end);
                        }
                        else
                        {
                            this.lines.Add("\t\twhile(num_vlds_" + name + " != num_lines_" + name + ");");
                            this.lines.Add("\t\t\t@posedge(" + di.ClockSync.Name + ");");
                            this.lines.Add("\t\t\tif(" + di.ValidOut.Name + ") begin");
                            this.lines.Add("\t\t\t\t$fdisplay(fid_out_" + name + ", \"" + this.formatOut + "\", " + this.dos);
                            this.lines.Add("\t\t\t\tnum_vlds_" + name + " <= num_vlds_" + name + " + 1;");
                            this.lines.Add("\t\t" + end);
                        }

                        this.lines.Add("\t" + end);

                        this.lines.Add(endtask + " : " + name);
                        this.lines.Add("");
                    }
                }
            }
        }

        private void AddFileInput()
        {
            if (this.ModuleFile.TestCases.Any(di => di.DataVector != null))
            {
                this.lines.Add(generatedToAdaptComment);
                this.lines.Add("//Tasks for reading from input data files - modify for your needs");
                foreach (TestCase di in this.ModuleFile.TestCases)
                {
                    if (di.DataVector != null && di.DataIns.FirstOrDefault() != null)
                    {
                        string name = di.DataIns.FirstOrDefault().Name + "_" + di.DataVector.Split('\\').LastOrDefault().Replace(".txt", "");

                        this.lines.Add(task + name + "();");

                        this.lines.Add("\t\tstring line_" + name + ";");
                        this.lines.Add("\t\tinteger fid_" + name + " = $fopen(\"" + di.DataVector.Replace("\\", "/") + "\",\"r\");");
                        this.lines.Add("\t\tif(fid_" + name + " == 0) begin");
                        this.lines.Add("\t\t\t$display(\"Error opening file - could not open.\");");
                        this.lines.Add("\t\t\t$stop;");
                        this.lines.Add("\t" + end + " else begin");
                        this.lines.Add("\t\t\t$display(\"File " + di.DataVector.Replace("\\", "/") + " opened successfully.\");");
                        this.lines.Add("\t" + end);

                        this.FormatsForFileIO(di);

                        if (di.Loop)
                        {
                            this.lines.Add(forever);
                            this.lines.Add("\t\t\t@posedge(" + di.ClockSync.Name + ");");
                            this.lines.Add("\t\t\tif(" + di.ValidIn.Name + "_pre) begin");
                            this.lines.Add("\t\t\t\tif($feof(fid_" + name + ")) begin");
                            this.lines.Add("\t\t\t\t\t$fclose(fid_" + name + ");");
                            this.lines.Add("\t\t\t\t\tfid_" + name + " = $fopen(\"" + di.DataVector.Replace("\\", "/") + "\",\"r\");");
                            this.lines.Add("\t\t\t\t\tif(fid_" + name + " == 0) begin");
                            this.lines.Add("\t\t\t\t\t\t$display(\"Error opening file - could not open.\");");
                            this.lines.Add("\t\t\t\t\t\t$stop;");
                            this.lines.Add("\t\t\t\t" + end + " else begin");
                            this.lines.Add("\t\t\t\t\t\t$display(\"File " + di.DataVector.Replace("\\", "/") + " opened successfully.\");");
                            this.lines.Add("\t\t\t\t" + end);
                            this.lines.Add("\t\t\t" + end + " else if($fgets(line_" + name + ", fid_" + name + ")) begin");
                                this.lines.Add("\t\t\t\tvoid'($sscanf(line_" + name + ", \"" + this.formatIn + "\", " + this.dis);
                            this.lines.Add("\t\t" + end + " else begin");
                            foreach(Port inp in di.DataIns)
                                this.lines.Add("\t\t\t" + inp.Name + " <= '0;");
                            this.lines.Add("\t\t" + end);
                        }
                        else
                        {
                            this.lines.Add("\t\t\twhile(!$feof(fid_" + name + ")) begin");
                            this.lines.Add("\t\t\t\t@posedge(" + di.ClockSync.Name + ");");
                            this.lines.Add("\t\t\t\tif(" + di.ValidIn.Name + "_pre) begin");
                            this.lines.Add("\t\t\t\t\tif($fgets(line_" + name + ", fid_" + name + ")) begin");
                            this.lines.Add("\t\t\t\t\t\tvoid'($sscanf(line_" + name + ", \"" + this.formatIn + "\", " + this.dis);
                            this.lines.Add("\t\t\t\t" + end + " else begin");
                            foreach (Port inp in di.DataIns)
                                this.lines.Add("\t\t\t\t\t\t" + inp.Name + " <= '0;");
                            this.lines.Add("\t\t\t\t" + end);
                            this.lines.Add("\t\t\t" + end + " else begin");
                            foreach (Port inp in di.DataIns)
                                this.lines.Add("\t\t\t\t\t" + inp.Name + " <= '0;");
                            this.lines.Add("\t\t\t" + end);
                            this.lines.Add("\t\t" + end);
                            this.lines.Add("\t\t\t$fclose(fid_" + name + ");");
                        }                                        
                        
                        this.lines.Add("\t" + end);
                                               
                        this.lines.Add(endtask + " : " + name);
                        this.lines.Add("");
                    }
                }
            }
        }

        #endregion

        public FileGen(ModuleFile moduleFile, string tbFileName)
        {
            this.ModuleFile = moduleFile;
            this.TbFileName = tbFileName;
            this.lines = new List<string>();
        }

        public bool GenerateFile()
        {
            this.lines = new List<string>();

            //create all lines of code
            this.AddHeader();
            this.AddParamsAndConnections();
            this.AddDut();
            this.AddClocks();
            this.AddInitialBlock();
            this.AddFileInput();
            this.AddFooter();

            //put code in tb file
            return this.SaveFile();
        }
    }
}
